fix(deps): use PEP 508 direct-URL syntax for safe-eth-py
The previous '#egg=name[extras]' fragment form was deprecated long ago
and is now rejected by pip 26.x:

    error: invalid-egg-fragment
    × The 'safe-eth-py[django]' egg fragment is invalid
    ╰─> from 'git+https://github.com/protofire/safe-eth-py.git@iotex#egg=safe-eth-py[django]'

The Dockerfile runs 'pip install -U pip' before installing deps, so it
always pulls latest pip and broke as soon as 26.1.1 was released. Switch
to the PEP 508 'name[extra] @ URL' form which pip 26.x accepts and older
versions also understand.